### PR TITLE
COMMERCE-8207,COMMERCE-8566,COMMERCE-8565 | Master

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-8207
https://issues.liferay.com/browse/COMMERCE-8566
https://issues.liferay.com/browse/COMMERCE-8565
Submit for master.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
Reviewing

**Comment by nikki-pru** [comment]
https://github.com/nikki-pru/liferay-portal/pull/254

**Pull request closed without merging**
