### PR TITLE
COMMERCE-7950

### PR DESCRIPTION
**Pull request by LeandroTravassos**
https://issues.liferay.com/browse/COMMERCE-7950

### CODE REVIEW

**Comment by LeandroTravassos** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
Hey @LeandroTravassos. We should be using "And given" for any additional steps after the first Given task. So you should have 
"And given the user set a widget page as Default Product Display Page by navigating to Channels page". Also for the task after that where you change the Default Product Display Page again.

**Comment by Kvale1733** [comment]
Also @LeandroTravassos, I see your macro to remove the Product Display Page asserts that "None" displays to check if it worked. But the Then task also does this with the CommerceEntry.assertDefaultProductDisplayPage(pageName = "None") line. I discussed this with Nikki and we think it would be better if you removed this line from the removeProductDisplayPage macro and just keep it in the test so it doesn't run twice.

**Comment by LeandroTravassos** [comment]
ci:test:sf

**Comment by LeandroTravassos** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
hey @nikki-pru changes have been made. I think it's ready to forward.

**Comment by nikki-pru** [comment]
ci:Forward

**Comment by Kvale1733** [comment]
hey @nikki-pru I think it's not forwarding because the F in "Forward" needs to be lowercase.

**Comment by nikki-pru** [comment]
oh thanks for the catch

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
