### PR TITLE
master-commerce-8256

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/COMMERCE-8286
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
Hi @chaowang-123, thanks for the test! A few changes:

1. The test name is correct, but please capitalize `Cancel` so the test name should be `CanCancelTheCreationOfANewEntry `
2. On the task blocks:
```
task ("Given I am creating a new Terms and Conditions entry") {
   lines 149-159
}

task ("When I cancel creating the entry") {
   lines 153-156
}

task ("Then the entry should not be created") {
   CommerceNavigator.gotoPortlet(
	category = "Order Management",
	portlet = "Terms and Conditions");

   CommercePaymentTerms.viewNoPG();
}
```

Great job on this!

**Comment by chaowang-123** [comment]
> Hi @chaowang-123, thanks for the test! A few changes:
> 
> 1. The test name is correct, but please capitalize `Cancel` so the test name should be `CanCancelTheCreationOfANewEntry `
> 2. On the task blocks:
> 
> ```
> task ("Given I am creating a new Terms and Conditions entry") {
>    lines 149-159
> }
> 
> task ("When I cancel creating the entry") {
>    lines 153-156
> }
> 
> task ("Then the entry should not be created") {
>    CommerceNavigator.gotoPortlet(
> 	category = "Order Management",
> 	portlet = "Terms and Conditions");
> 
>    CommercePaymentTerms.viewNoPG();
> }
> ```
> 
> Great job on this!

Thanks, i will update this.

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/114781

**Pull request closed without merging**
