### PR TITLE
COMMERCE-7702 | master

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/COMMERCE-7702
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:relevant

**Comment by nikki-pru** [comment]
ci:test:stable

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
ci:test:relevant

**Comment by nikki-pru** [comment]
Commerce functional test failures are not related. [The new test passes](https://testray.liferay.com/home/-/testray/case_results/1885280986?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1885279377%26testrayRunId%3D1885280035%26cur%3D2%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse).

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
