### PR TITLE
COMMERCE-8146, COMMERCE-8147 | master

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-8146
https://issues.liferay.com/browse/COMMERCE-8147
Submit for master only.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
Reviewing in https://github.com/nikki-pru/liferay-portal/pull/296

**Pull request closed without merging**
