### PR TITLE
COMMERCE-7760, COMMERCE-7766, COMMERCE-7761, COMMERCE-7768, COMMERCE-7763, COMMERCE-7765, COMMERCE-7759 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/COMMERCE-7760
https://issues.liferay.com/browse/COMMERCE-7766
https://issues.liferay.com/browse/COMMERCE-7761
https://issues.liferay.com/browse/COMMERCE-7768
https://issues.liferay.com/browse/COMMERCE-7763
https://issues.liferay.com/browse/COMMERCE-7765
https://issues.liferay.com/browse/COMMERCE-7759

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
Discussed changes with @Kvale1733 .

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@nikki-pru Changes have been made 😊

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
