### PR TITLE
COMMERCE-9829,COMMERCE-9876 | master

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-9829
https://issues.liferay.com/browse/COMMERCE-9876
Submit for master only.

previous: https://github.com/nikki-pru/liferay-portal/pull/457

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Hello @nikki-pru,

Looks like the commerce-relevant tests are not related to this pull. Please double-check when you're free! Thanks! :)

**Comment by nikki-pru** [comment]
All related tests [passing](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1985240403&testrayRunId=1985240618&testrayCaseName=LocalFile.CommerceAccountOrderDefaults)! Thanks @jaydawu

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
