### PR TITLE
LPS-126222 | master

### PR DESCRIPTION
**Pull request by brittneyq**
https://issues.liferay.com/browse/LPS-126222

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:relevant

**Comment by nikki-pru** [comment]
@brittneyq please squash both commits into one. Thanks

**Comment by david-gutierrez-mesa** [comment]
@nikki-pru @brittneyq this has already been sent to BChan. See https://github.com/brianchandotcom/liferay-portal/pull/98443#issuecomment-773959662 and https://github.com/david-gutierrez-mesa/liferay-portal/pull/118

Thank you both for your help!! :-)

**Comment by brittneyq** [comment]
Thank you for the fixes @david-gutierrez-mesa !

**Pull request closed without merging**
