### PR TITLE
LPS-174856 | master

### PR DESCRIPTION
**Pull request by allen-nagtalon**
https://issues.liferay.com/browse/LPS-174856

### CODE REVIEW

**Comment by allen-nagtalon** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:digital-signature

**Comment by nikki-pru** [comment]
Started reviewing!

**Comment by nikki-pru** [comment]
ci:test:digital-signature:no-compile

**Comment by nikki-pru** [comment]
ci:test:digital-signature:nocompile

**Comment by allen-nagtalon** [comment]
ci:forward

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
