### PR TITLE
LPS-173737 | master

### PR DESCRIPTION
**Pull request by allen-nagtalon**
https://issues.liferay.com/browse/LPS-173737

### CODE REVIEW

**Comment by nikki-pru** [comment]
@allen-nagtalon, please remove the MyTestFile file from the commits.

**Comment by allen-nagtalon** [comment]
The commit with the MyTestFile file has been omitted, and a new commit with the proper changes to Forms.testcase has been pushed.

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:stable

**Comment by allen-nagtalon** [comment]
Files have been reformatted via the proper ant commands; changes have been pushed via a new commit.

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
