### PR TITLE
COMMERCE-7021 | Add new test to upload an already mapped new image.

### PR DESCRIPTION
**Pull request by bbqbronson**
https://issues.liferay.com/browse/COMMERCE-7021

### CODE REVIEW

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
@bronsonsoda , please edit. See [Slack](https://liferay.slack.com/archives/GSCJYT2KD/p1640071084008300). 
Thanks

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
@bronsonsoda, There's a conflicting file. Please rebase your branch thanks.

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
Requested changes on Slack

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
