### PR TITLE
Commerce-7100-Update | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/COMMERCE-7100

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by nikki-pru** [comment]
ci:forward

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
