### PR TITLE
Commerce-9613 Refactoring Product Card and Mini Cart tests

### PR DESCRIPTION
**Pull request by kristinonias**
https://issues.liferay.com/browse/COMMERCE-9613

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
@kristinonias , please check Testray results above. Looks like there are failures related to Mini Cart and Product Card.

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
[CommerceProductCard](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1957158482&testrayRunId=1957159639&testrayCaseName=LocalFile.CommerceProductCard) and [CommerceMiniCart](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1957158482&testrayRunId=1957159639&testrayCaseName=LocalFile.CommerceMiniCart) tests are passing 🎉
Other failures are not related.

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
