### PR TITLE
LPS-175320 | master

### PR DESCRIPTION
**Pull request by allen-nagtalon**
https://issues.liferay.com/browse/LPS-175320

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test:digital-signature

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by allen-nagtalon** [comment]
ci:test:digital-signature:nocompile

**Comment by nikki-pru** [comment]
ci:test:digital-signature:nocompile

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
Testing here: https://github.com/nikki-pru/liferay-portal/pull/735

**Pull request closed without merging**
