### PR TITLE
LPS-122073 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LPS-122073

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by nikki-pru** [comment]
Changes sent in under https://github.com/nikki-pru/liferay-portal/pull/50

**Pull request closed without merging**
