### PR TITLE
LPS-126217

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LPS-126217

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by nikki-pru** [comment]
@nkkwon for the localized title, please put a title written in the selected language. See @Tim-Cao's comment on a similar test here: https://github.com/brianchandotcom/liferay-portal/pull/98443#discussion_r570548403

**Comment by nikki-pru** [comment]
@nkkwon, following up on this one. 
Please send changes to @emanuelfisilva so we can proceed with closing out the task.

**Comment by emanuelfisilva** [comment]
Received https://github.com/emanuelfisilva/liferay-portal/pull/46
Thanks!

**Pull request closed without merging**
