### PR TITLE
COMMERCE-8358, COMMERCE-7983 | master

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-8358
https://issues.liferay.com/browse/COMMERCE-7983
Submit for master only.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
Testing in nikki-pru#306

**Pull request closed without merging**
