### PR TITLE
LPS-126228 | master

### PR DESCRIPTION
**Pull request by joepak**
[LPS-126228](https://issues.liferay.com/browse/LPS-126228)

### CODE REVIEW

**Comment by joepak** [comment]
ci:test:sf

**Comment by joepak** [comment]
ci:test:relevant

**Comment by joepak** [comment]
ci:test:sf

**Comment by joepak** [comment]
ci:test:relevant:nocompile

**Comment by nikki-pru** [comment]
Forwarded: https://github.com/Tim-Cao/liferay-portal/pull/619

**Pull request closed without merging**
