### PR TITLE
COMMERCE-7022 Add new test CPCommerceProductDiagrams#UseExpand

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/COMMERCE-7022

### CODE REVIEW

**Comment by nkkwon** [comment]
Test failing in other parts locally and others are not able to reproduce issue

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:relevant

**Comment by nikki-pru** [comment]
ci:test:stable

**Comment by nkkwon** [comment]
Pushed up new fix, please test locally thank you!

**Comment by nkkwon** [comment]
Will fix conflicts

**Pull request closed without merging**
