### PR TITLE
COMMERCE-7100-Update | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/COMMERCE-7100

### CODE REVIEW

**Comment by Kvale1733** [comment]
@nikki-pru Resending with changes to dependency file. BChan wanted it all lowercase. I therefore also had to make changes to the diagram image macro to take the lowercase name.

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
