### PR TITLE
LRQA-42205 Bookmarks Release Testing

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/LRQA-42205

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test

**Comment by nikki-pru** [comment]
ci:test

**Comment by nikki-pru** [comment]
@patriciajeanperez i'm retesting because i forgot to take out some of the tests. Feel free to grab this branch if you need it.

**Comment by patriciajeanperez** [comment]
Hi @nikki-pru, thank you for running our bookmarks tests on all certified environments!

Our tests that have portal.acceptance set to false were not ran, so I'm going to run these tests again including those missing tests. Results should be here: https://github.com/patriciajeanperez/liferay-portal/pull/97

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
