### PR TITLE
COMMERCE-8303 | master

### PR DESCRIPTION
**Pull request by bbqbronson**
https://issues.liferay.com/browse/COMMERCE-8303

### CODE REVIEW

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by bronsonsoda** [comment]
ci:test:relevant

**Comment by bronsonsoda** [comment]
ci:stop

**Comment by bronsonsoda** [comment]
ci:test:relevant

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by bronsonsoda** [comment]
logs kinda look just like a timeout/address request failures 🤔

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
