### PR TITLE
COMMERCE-8153 | master

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/COMMERCE-8153
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
Reviewing in https://github.com/nikki-pru/liferay-portal/pull/296

**Comment by nikki-pru** [comment]
Testing in nikki-pru#306

**Pull request closed without merging**
