### PR TITLE
COMMERCE-9873 | master

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-9873
Submit for master only.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Hi @nikki-pru, the related test ([LocalFile.CommerceAccountOrderDefaults#CanSetDefaultAddressFromDetailsTab](https://testray.liferay.com/home/-/testray/case_results/2031230218?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DCanSetDefaultAddressFromDetailsTab%26testrayBuildId%3D2031229579%26testrayRunId%3D2031229629%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)) passed on CI. Please review, thanks! :)

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
