### PR TITLE
COMMERCE-6925 Disable AddToCart.js test

### PR DESCRIPTION
**Pull request by nikki-pru**

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test:stable

**Comment by nikki-pru** [comment]
ci:test:stable

**Comment by brianchandotcom** [comment]
@nikki-pru I merged in this ignore for now. 

@alecsloan please fix tomorrow. Thx.

**Comment by alecsloan** [comment]
Hey @brianchandotcom I've already committed removing the test, I'm going to send it directly to you if that's alright.

**Comment by nikki-pru** [comment]
Closing this. 
The remove was sent in this PR: https://github.com/brianchandotcom/liferay-portal/pull/104660.
Thanks!

**Pull request closed without merging**
