### PR TITLE
COMMERCE-9885 | master

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/COMMERCE-9885
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:commerce-functional

**Comment by chaowang-123** [comment]
Hi @nikki-pru, Looks like the commerce-relevant tests are not related to this pull.

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
