### PR TITLE
COMMERCE-8227 | master 

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/COMMERCE-8227
https://issues.liferay.com/browse/COMMERCE-8268 (Refactor Ticket CPCommerceProductDiagrams#EditTheDefaultSettingForPinsCreation)
https://issues.liferay.com/browse/COMMERCE-8269 (Refactor Ticket CPCommerceProductDiagrams#UseZoomAndDragBackground)

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:commerce-functional

**Comment by epark18** [comment]
ci:stop

**Comment by epark18** [comment]
ci:test:commerce-functional

**Comment by epark18** [comment]
ci:test:commerce-functional

**Comment by epark18** [comment]
All but one of the ProductDiagram tests passed. @bronsonsoda can submit a test fix for _LocalFile.CPCommerceProductDiagrams#UploadAlreadyMappedNewImage_ should be an easy change. Only two tests need to be quarantined.

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
