### PR TITLE
master-commerce-8283 | master-commerce-8296

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-8283
https://issues.liferay.com/browse/COMMERCE-8296
https://issues.liferay.com/browse/COMMERCE-8295
Submit for master.
(Sorry it was two test commits for COMMERCE-8283/COMMERCE-8296, but cherry pick ate one. I have no idea with what happened.)

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
Reviewing

**Comment by nikki-pru** [comment]
Testing here: nikki-pru#184

**Comment by nikki-pru** [comment]
Forwarded: https://github.com/brianchandotcom/liferay-portal/pull/114656

**Pull request closed without merging**
