### PR TITLE
COMMERCE-9829,COMMERCE-9876 | master

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-9829
https://issues.liferay.com/browse/COMMERCE-9876
Submit for master only.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
Hello @nikki-pru,

Looks like the commerce relevant tests are not related to this pull. I'm not sure if the analysis that I did is right. If you have time, please double-check! Thanks! :)

**Comment by nikki-pru** [comment]
Thanks @jaydawu . Sorry for the delay on this. I was out sick for a while.

For the test covering (COMMERCE-9829](https://issues.liferay.com/browse/COMMERCE-9829) can you split the test into two? One test for each scenario mentioned on the ticket.

**Comment by jaydawu** [comment]
@nikki-pru sure, I will do that, thank you! Hope you feel better now! :)

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
