### PR TITLE
Testing Round 3 of commits that got merged. 

### PR DESCRIPTION
**Pull request by nikki-pru**
Testing:
https://liferay.atlassian.net/browse/LPD-15752
https://liferay.atlassian.net/browse/LPD-17511
https://liferay.atlassian.net/browse/LPD-17739
https://liferay.atlassian.net/browse/LPD-17668
https://liferay.atlassian.net/browse/LPD-17733
https://liferay.atlassian.net/browse/LPD-17698
https://liferay.atlassian.net/browse/LPD-17697
https://liferay.atlassian.net/browse/LPD-17410

This also contains new tests from https://liferay.atlassian.net/browse/LPD-17768 for LPD-15752

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Ran `ci:test` at https://github.com/nikki-pru/liferay-portal/pull/1081

**Pull request closed without merging**
